version: 2

project_name: buck

builds:
  - main: .
    binary: buck
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/chinhstringee/buck/cmd.Version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz

brews:
  - name: buck
    repository:
      owner: chinhstringee
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/chinhstringee/buck
    description: Multi-repo orchestration tool for Bitbucket
    license: MIT

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
